server.port=${PORT:8080}
info.app.name=spring
info.app.description=This is my first spring boot application
info.app.version=1.0.0

vaadin.frontend.hotdeploy=true
vaadin.productionMode=false

# To improve the performance during development.
# For more information https://vaadin.com/docs/flow/spring/tutorial-spring-configuration.html#special-configuration-parameters
# vaadin.whitelisted-packages= org/vaadin/example
logging.level.root=error

pring.activemq.broker-url=tcp://localhost:61616

spring.activemq.user=admin

spring.activemq.password=admin

jms.queue-name=email-queue
active-mq.topic=user-topic


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=reniers.joren@gmail.com
spring.mail.password=lncu zuih groa hwxt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000